[tool.poetry]
name = "p2pfl"
version = "0.2.2"
description = "A p2p federated learning framework"
authors = ["Pedro Guijas <pguijas@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
homepage = "https://pguijas.github.io/p2pfl/"
repository = "https://github.com/pguijas/p2pfl"
documentation = "https://pguijas.github.io/p2pfl/doc"
keywords = ["federated learning", "fl", "peer to peer", "p2p", "decentralized", "data privacy", "data security", "pytorch"]

[tool.poetry.dependencies]
python = "^3.9"
pytorch-lightning = "^1.2.1"
grpcio = "^1.62.0"
grpcio-tools = "^1.62.0"
torch = "^2.2.1"
torchvision = "^0.17.1"
torchmetrics = "^1.3.1"
matplotlib = "^3.8.3"
psutil = "^5.9.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
ruff = "^0.5.1"
mypy = "^1.8.0"
mypy-protobuf = "^3.5.0"
types-protobuf = "^4.24.0.20240302"

[tool.poetry.group.docs.dependencies]
Sphinx = "^7.2.6"
myst-parser = "^2.0.0"
furo = "^2024.1.29"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

#[tool.poetry.extras]
#torch = ["torch", "torchvision", "torchmetrics", "pytorch-lightning"]